services:
  - type: web
    name: project-dagger
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app --config gunicorn_config.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
      - key: FIREBASE_DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false 